services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HeimrichHannot\MigrationBundle\Command\NewsCategoriesMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\NewsArchiveMenuToFilterMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\OwlCarouselToTinySliderMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\TabsToTabControleMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\NewsTagsMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\NewsListModuleMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\NewsReaderModuleMigrationCommand: ~
