services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HeimrichHannot\MigrationBundle\Command\NewsArchiveMenuToFilterMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\OwlCarouselToTinySliderMigrationCommand: ~
  HeimrichHannot\MigrationBundle\Command\TabsToTabControleMigrationCommand: ~