services:
  _defaults:
    autoconfigure: true

# Commands

  ## Module Commands

  huh.migration.module.newsplus:
    class: HeimrichHannot\MigrationBundle\Command\NewsPlusModuleMigrationCommand
    arguments: ['@contao.framework', '@huh.utils.model', '@translator', '@huh.utils.container']

  huh.migration.modulestoblock:
    class: HeimrichHannot\MigrationBundle\Command\MoveModulesToBlockCommand
    arguments: ['@contao.framework', '@huh.utils.model']
