services:
  _defaults:
    autoconfigure: true

# Commands

  ## Module Commands

  huh.migration.module.newsreader:
    class: HeimrichHannot\MigrationBundle\Command\NewsReaderModuleMigrationCommand
    arguments: ['@contao.framework']

  huh.migration.module.newsplus:
    class: HeimrichHannot\MigrationBundle\Command\NewsPlusModuleMigrationCommand
    arguments: ['@contao.framework', '@huh.utils.model', '@translator', '@huh.utils.container']

  huh.migration.modulestoblock:
    class: HeimrichHannot\MigrationBundle\Command\MoveModulesToBlockCommand
    arguments: ['@contao.framework', '@huh.utils.model']

  ## Database Commands

  huh.migration.database.newscategories:
    class: HeimrichHannot\MigrationBundle\Command\NewsCategoriesMigrationCommand
    arguments: ['@contao.framework']
  huh.migration.database.newstags:
    class: HeimrichHannot\MigrationBundle\Command\NewsTagsMigrationCommand
    arguments: ['@service_container']
